[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
multiple_tokens = "HpcdH7e76Dep273mkjbyJqGB5QE3cPAXCB8LmDnwj3Hd"

[programs.devnet]
multiple_tokens = "HpcdH7e76Dep273mkjbyJqGB5QE3cPAXCB8LmDnwj3Hd"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
