[toolchain]

[features]
resolution = true
skip-lint = false
seed = true

[programs.localnet]
multiple_tokens = "GqwLRbiFFcAujKPm4NchYfLRhJ6ztTtaPyMADamd6e3"

[programs.devnet]
multiple_tokens = "GqwLRbiFFcAujKPm4NchYfLRhJ6ztTtaPyMADamd6e3"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
test-trading = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/trading.ts"
 